### ISSUE TITLE
!

### ISSUE THREAD

**Issue by iP010** [evanknapke/iOS-Photo-Extractor#1]
```
xception in thread Thread-90:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_file.py", line 537, in _prefetch_thread
    num = self.sftp._async_request(
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 837, in _async_request
    self._send_packet(t, msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp.py", line 198, in _send_packet
    self._write_all(out)
  File "/usr/lib/python3/dist-packages/paramiko/sftp.py", line 162, in _write_all
    n = self.sock.send(out)
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 1208, in _send
    self.transport._send_user_message(m)
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1863, in _send_user_message
    self._send_message(data)
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1839, in _send_message
    self.packetizer.send_message(data)
  File "/usr/lib/python3/dist-packages/paramiko/packet.py", line 431, in send_message
    self.write_all(out)
  File "/usr/lib/python3/dist-packages/paramiko/packet.py", line 367, in write_all
    raise EOFError()
EOFError
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 843, in _read_response
    t, data = self._read_packet()
  File "/usr/lib/python3/dist-packages/paramiko/sftp.py", line 207, in _read_packet
    data = self._read_all(size)
  File "/usr/lib/python3/dist-packages/paramiko/sftp.py", line 188, in _read_all
    raise EOFError()
EOFError
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "tt.py", line 56, in <module>
    sftp.get(os.path.join(REMOTEPATH, file), local_path, callback=None)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 802, in get
    size = self.getfo(remotepath, fl, callback)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 781, in getfo
    return self._transfer_with_callback(
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 678, in _transfer_with_callback
    data = reader.read(32768)
  File "/usr/lib/python3/dist-packages/paramiko/file.py", line 219, in read
    new_data = self._read(read_size)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_file.py", line 182, in _read
    data = self._read_prefetch(size)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_file.py", line 162, in _read_prefetch
    self.sftp._read_response()
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 845, in _read_response
    raise SSHException("Server connection dropped: {}".format(e))
paramiko.ssh_exception.SSHException: Server connection dropped:
```

**Comment by evanknapke** [comment]
The EOFError is an issue with the Paramiko library that I used for this project. I currently, have not been able to come up with a work around but I am well aware that this issue can arise.
